### ISSUE TITLE
different job scheduler than Slurm - using PBS Pro

### ISSUE THREAD

**Issue by spatts14** [FrancisCrickInstitute/TRACERx-PHLEX#44]
Hi all,

Really excited to give TYPEx a try -thanks for developing!

However, we are hitting an issue running it on our Imperial College London HPC. I raised a ticket with our ICT team and they suggested we contact you as we are getting the error below. We use a different job scheduler called PBS Pro, rather than Slurm job scheduler. 

They suspected that the program had been written for the Crick research computing infrastructure and what needs changing to work on Imperial infrastructure. 
```
Aug-22 09:34:03.025 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 'TYPEx:TISSEG:preprocess_panck'

Caused by:

  java.io.IOException: Cannot run program "sbatch" (in directory "/rds/general/user/sep22/home/Other/GitHub/work/a3/153f4792b4fd5143fade0cb35e8549"): error=2, No such file or directory
```

 Thanks in advance for your help!

**Comment by Precancer** [comment]
Hi Sara,

Thanks for trying out TYPEx! 
The pipeline should work with different types of job scheduler. Have you tried setting `executor` to `executor = 'pbspro'` in the file TYPEx/conf/base.config?
The following config file from the nf-core community for Imperial's cluster may be useful to adjust the memory requirements in the file above: 
https://nf-co.re/configs/imperial/

Let me know if that helps.

**Comment by spatts14** [comment]
We ended up running it on the Crick HPC but will keep this in mind! Thanks!
